import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {flushSync} from 'react-dom';
import {GlobeHemisphereWest, MagnifyingGlass, Plus, Minus, Crosshair, X, ArrowSquareOut, Play, Pause, SlidersHorizontal, Info, CaretDown, Lightning, Factory, Plant, Buildings, Car, Trash, House, Wind, ArrowsLeftRight, Eye, Stack, Heartbeat, Check} from '@phosphor-icons/react';
import Globe from '../Globe';
import {cities,systems,concentrations,seasons,evidence} from '../data';
import '../styles.css';
const sourceIcons=[Lightning,Factory,Plant,Buildings,Car,Trash,House,Wind];
function App(){
 const [city,setCity]=useState(cities[0]),[active,setActive]=useState(systems.map(s=>s.id)),[selected,setSelected]=useState(null),[mode,setMode]=useState('atmosphere'),[zoom,setZoom]=useState(0),[focus,setFocus]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[year,setYear]=useState(2024),[month,setMonth]=useState(10),[playing,setPlaying]=useState(false),[tab,setTab]=useState('air'),[modal,setModal]=useState(null),[compare,setCompare]=useState(cities[2]),[scenario,setScenario]=useState(0),[mobilePanel,setMobilePanel]=useState(null),[ready,setReady]=useState(false);
 const liveState=useRef(null);liveState.current={city,active,selected,year,month,scenario};
 const system=systems.find(s=>s.id===selected),pm=concentrations(city,year,month,scenario);
 const chooseCity=c=>{setCity(c);setZoom(1);setFocus(f=>f+1);setSearch(false);setQuery('');};
 const chooseSystem=id=>{setSelected(selected===id?null:id);if(!active.includes(id))setActive(a=>[...a,id]);setMode('atmosphere');};
 const toggle=id=>{if(selected===id&&active.includes(id))setSelected(null);setActive(a=>a.includes(id)?a.filter(i=>i!==id):[...a,id]);};
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>{const current=liveState.current;if(current.month===11){setYear(current.year===2024?2015:current.year+1);setMonth(0);}else{setMonth(current.month+1);}},1100);return()=>clearInterval(id);},[playing]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape'){setModal(null);setSearch(false);setMobilePanel(null);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;const dialog=document.querySelector('[role=dialog]');const focusable=()=>Array.from(dialog.querySelectorAll('button,a,input,select,[tabindex]')).filter(el=>!el.disabled&&el.offsetParent!==null);focusable()[0]?.focus();const trap=e=>{if(e.key!=='Tab')return;const els=focusable(),first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};dialog.addEventListener('keydown',trap);return()=>{dialog.removeEventListener('keydown',trap);previous?.focus();};},[modal]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const read=()=>{const s=liveState.current;return{city:s.city.name,cityId:s.city.id,visibleSystems:s.active,trace:s.selected,year:s.year,month:s.month+1,pm25:concentrations(s.city,s.year,s.month,s.scenario),dataStatus:'illustrative, invented'};};const tools=[{name:'read_atlas_state',title:'Read atmosphere exploration',description:'Read the selected city, visible systems and fictional concentration.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:read},{name:'explore_atmosphere',title:'Explore a city and system',description:'Select a demo city, pollution system and illustrative date. Changes the same globe and inspector as the visible controls.',inputSchema:{type:'object',properties:{cityId:{type:'string',enum:cities.map(c=>c.id)},systemId:{type:'string',enum:systems.map(s=>s.id)},year:{type:'integer',minimum:2015,maximum:2024},month:{type:'integer',minimum:1,maximum:12}},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');for(const key of Object.keys(input))if(!['cityId','systemId','year','month'].includes(key))throw new Error('Unknown field');const c=input.cityId===undefined?null:cities.find(c=>c.id===input.cityId);const sys=input.systemId===undefined?null:systems.find(s=>s.id===input.systemId);if(input.cityId!==undefined&&!c)throw new Error('Unknown demo city');if(input.systemId!==undefined&&!sys)throw new Error('Unknown system');if(input.year!==undefined&&(!Number.isInteger(input.year)||input.year<2015||input.year>2024))throw new Error('Year outside demo range');if(input.month!==undefined&&(!Number.isInteger(input.month)||input.month<1||input.month>12))throw new Error('Invalid month');flushSync(()=>{if(c){setCity(c);setZoom(1);setFocus(f=>f+1);}if(sys){setSelected(sys.id);setActive(a=>a.includes(sys.id)?a:[...a,sys.id]);setMode('atmosphere');}if(input.year!==undefined)setYear(input.year);if(input.month!==undefined)setMonth(input.month-1);setPlaying(false);});return read();}}];tools.forEach(tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();},[]);
 const resultCities=cities.filter(c=>(c.name+' '+c.country).toLowerCase().includes(query.toLowerCase()));
 return <main className="atlas-app">
  <Globe city={city} active={active} selected={selected} mode={mode} zoom={zoom} focus={focus} year={year} month={month} scenario={scenario} onCity={chooseCity} onReady={()=>setReady(true)}/>
  <header className="topbar flex items-center justify-between">
   <div className="brand flex items-center gap-3"><GlobeHemisphereWest size={32} weight="thin"/><div><h1>Who owns the air<span>?</span></h1><p>AN EXPLORATION OF INVISIBLE SYSTEMS</p></div></div>
   <div className="top-actions flex items-center gap-3"><span className="demo-badge"><span/>Illustrative data</span><button aria-label="About this atlas" className="about-button" onClick={()=>setModal('about')}><Info size={19}/><span>About this atlas</span></button></div>
  </header>
  <div className="location-search">
   <div className="search-input flex items-center gap-3"><MagnifyingGlass size={19}/><input aria-label="Search cities" placeholder="Find the air around you" value={query} onFocus={()=>setSearch(true)} onChange={e=>{setQuery(e.target.value);setSearch(true);}} onKeyDown={e=>{if(e.key==='Enter'&&resultCities[0])chooseCity(resultCities[0]);}}/><span className="search-hint">CITY</span></div>
   {search&&<div className="search-results"><div className="results-heading">{query?'MATCHING PLACES':'EXPLORE A PLACE'}<button aria-label="Close search" onClick={()=>setSearch(false)}><X size={16}/></button></div>{resultCities.length?resultCities.map(c=><button className="search-result" key={c.id} onClick={()=>chooseCity(c)}><span>{c.name}<small>{c.country}</small></span><Crosshair size={18}/></button>):<p className="empty-search">No matching demo city. Try Delhi, London or Beijing.</p>}<p className="search-note">12 demo cities · no live location data</p></div>}
  </div>
  <aside className={`sources-panel panel ${mobilePanel==='systems'?'mobile-open':''}`} aria-label="Pollution systems">
   <div className="section-heading"><span>THE SYSTEMS IN YOUR AIR</span><button className="mobile-close" aria-label="Close systems" onClick={()=>setMobilePanel(null)}><X size={18}/></button></div>
   <h2>Follow a source.</h2><p className="panel-intro">Select a system to reveal its pathways.</p>
   <div className="source-list">{systems.map((s,i)=>{const Icon=sourceIcons[i];return <div key={s.id} className={`source-row ${selected===s.id?'source-selected':''}`} style={{'--source-color':s.color}}><button className="source-select" onClick={()=>chooseSystem(s.id)} aria-pressed={selected===s.id}><Icon size={20} weight="light"/><span>{s.name}</span>{selected===s.id&&<span className="trace-indicator"/>}</button><input type="checkbox" aria-label={`Show ${s.name} layer`} checked={active.includes(s.id)} onChange={()=>toggle(s.id)}/></div>;})}</div>
   <div className="source-foot flex items-center justify-between"><span>{active.length} of 8 layers visible</span><button onClick={()=>{setActive(active.length===8?[]:systems.map(s=>s.id));setSelected(null);}}>{active.length===8?'Hide all':'Show all'}</button></div>
   {system&&<div className="tracing-summary"><span className="eyebrow">TRACING {system.name.toUpperCase()}</span><p>{system.chemical}</p><button onClick={()=>setSelected(null)}>Clear trace <X size={13}/></button></div>}
  </aside>
  <div className="scene-topline"><span>EARTH / {zoom?'CITY ORBIT':'GLOBAL ORBIT'}</span><span>{String(Math.abs(city.lat)).padStart(5,'0')}° {city.lat>0?'N':'S'} &nbsp; {Math.abs(city.lon).toFixed(2)}° {city.lon>0?'E':'W'}</span></div>
  <div className="scene-caption"><span className="caption-rule"/><div><span className="eyebrow">{system?'A POSSIBLE PATHWAY':'ONE SHARED ATMOSPHERE'}</span><p>{system?system.title:'The air is a meeting place.'}</p></div></div>
  <aside className={`inspector panel ${mobilePanel==='place'?'mobile-open':''}`} aria-label="Selected location inspector">
   <div className="inspector-heading"><span className="section-heading">AIR AROUND</span><button className="mobile-close" aria-label="Close location" onClick={()=>setMobilePanel(null)}><X size={18}/></button><button className="locate-button" aria-label="Recenter on selected city" onClick={()=>{setFocus(f=>f+1);setZoom(1);}}><Crosshair size={19}/></button></div>
   <h2>{city.name}</h2><div className="city-meta"><span>{city.country}</span><span>{seasons[month]} {year}</span></div>
   <div className="inspector-tabs" role="tablist" aria-label="Location details" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const ids=['air','systems','impact'];const next=(ids.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3;setTab(ids[next]);e.currentTarget.querySelectorAll('button')[next].focus();}}>{[['air','Atmosphere'],['systems','Systems'],['impact','Impact']].map(([id,title])=><button role="tab" aria-selected={tab===id} id={`tab-${id}`} aria-controls={`panel-${id}`} key={id} tabIndex={tab===id?0:-1} onClick={()=>setTab(id)}>{title}</button>)}</div>
   <div role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`}>
   {tab==='air'&&<><div className="concentration"><span className="eyebrow">FINE PARTICLES · PM₂.₅</span><div><strong>{pm}</strong><span>µg/m³</span><span className="metric-art">ILLUSTRATIVE</span></div><p>A fictional monthly concentration.</p></div><div className="concentration-scale"><span/><span/><span/><span/><span/><i style={{left:Math.min(98,pm/100*100)+'%'}}/></div><div className="scale-labels"><span>Less</span><span>More particles</span></div><div className="air-composition"><div className="section-heading">A MIXTURE, NOT ONE SUBSTANCE</div><div className="constituent"><span className="constituent-dot soot"/><span>Soot & organic matter</span></div><div className="constituent"><span className="constituent-dot secondary"/><span>Sulfates & nitrates</span></div><div className="constituent"><span className="constituent-dot dust"/><span>Dust & trace metals</span></div><p>These can be parts of particulate matter, not separate additions to PM₂.₅.</p></div></>}
   {tab==='systems'&&<div className="system-details"><span className="eyebrow">FICTIONAL SOURCE MIX</span>{systems.map((s,i)=><button className="mix-row" key={s.id} onClick={()=>chooseSystem(s.id)}><span>{s.name}</span><span className="mix-bar"><i style={{width:city.profile[i]*3+'%',background:s.color}}/></span><strong>{city.profile[i]}%</strong></button>)}<p>Invented shares for exploration. Regional transport can contain emissions from other systems; these categories are a simplified demo, not a validated attribution model.</p></div>}
   {tab==='impact'&&<div className="impact-details"><Heartbeat size={30} weight="thin"/><h3>Small particles.<br/>Deep consequences.</h3><p>Fine particles can reach deep into the lungs. Exposure is linked to respiratory and cardiovascular harm.</p><p>Concentration in outdoor air is not the same as the dose a person inhales. Time, activity and indoor conditions matter.</p><a href={evidence[1].url} target="_blank" rel="noreferrer">Read the EPA evidence <ArrowSquareOut size={14}/></a><span className="impact-note">General context. No personal health or mortality estimates are modeled here.</span></div>}
   </div>
   {system&&<div className="selected-context" style={{'--source-color':system.color}}><div className="context-heading"><span>IN FOCUS</span><strong>{system.name}</strong></div><p>{system.description}</p><div className="formula">{system.formula}</div><span className="pathway-note">Schematic chemistry · not a local attribution</span></div>}
   <button className="compare-button" onClick={()=>{if(compare.id===city.id)setCompare(cities.find(c=>c.id!==city.id));setModal('compare');}}><ArrowsLeftRight size={18}/><span>Compare another place</span></button>
  </aside>
  <div className="scene-controls"><div className="view-switch" role="group" aria-label="Globe view"><button aria-pressed={mode==='atmosphere'} onClick={()=>setMode('atmosphere')}><Eye size={17}/><span>Atmosphere</span></button><button aria-pressed={mode==='terrain'} onClick={()=>setMode('terrain')}><GlobeHemisphereWest size={17}/><span>Earth</span></button></div><div className="zoom-controls"><button aria-label="Zoom in to city" onClick={()=>{setZoom(1);setFocus(f=>f+1);}}><Plus size={18}/></button><button aria-label="Zoom out to global orbit" onClick={()=>{setZoom(0);setFocus(f=>f+1);}}><Minus size={18}/></button><button aria-label="Reset globe view" onClick={()=>{setZoom(0);setFocus(f=>f+1);}}><Crosshair size={18}/></button></div></div>
  <div className="globe-instructions">Drag to rotate <span>·</span> Scroll to move closer <span>·</span> Select a place</div>
  <div className="mobile-panel-buttons"><button onClick={()=>setMobilePanel(m=>m==='systems'?null:'systems')}><Stack size={18}/>Systems</button><button onClick={()=>setMobilePanel(m=>m==='place'?null:'place')}><Crosshair size={18}/>{city.name}</button></div>
  <footer className="timeline-panel"><div className="timeline-title"><span className="eyebrow">TIME IN THE ATMOSPHERE</span><button className="play-button" aria-label={playing?'Pause timeline':'Play timeline'} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={17} weight="fill"/>:<Play size={17} weight="fill"/>}<span>{seasons[month].slice(0,3)} {year}</span></button></div><div className="time-track"><input type="range" min="2015" max="2024" step="1" value={year} aria-label="Illustrative year" onChange={e=>setYear(+e.target.value)}/><div className="year-labels">{[2015,2018,2021,2024].map(y=><button onClick={()=>setYear(y)} key={y}>{y}</button>)}</div></div><label className="month-select"><select aria-label="Month" value={month} onChange={e=>setMonth(+e.target.value)}>{seasons.map((m,i)=><option key={m} value={i}>{m}</option>)}</select><CaretDown size={14}/></label><button className="scenario-button" onClick={()=>setModal('scenario')}><SlidersHorizontal size={18}/><span>What if?</span>{scenario>0&&<i/>}</button></footer>
  <div className="bottom-note"><span>AN ATMOSPHERIC ATLAS</span><button onClick={()=>setModal('about')}>All values & pathways are illustrative. <span>Explore the method</span></button></div>
  {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className={`modal ${modal==='compare'?'compare-modal':''}`} role="dialog" aria-modal="true" aria-label={modal==='about'?'About this atlas':modal==='compare'?'Compare places':'Explore a hypothetical change'} onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={23}/></button>
   {modal==='about'&&<><span className="eyebrow">WHO OWNS THE AIR?</span><h2>An atlas of<br/>interdependence.</h2><p>The atmosphere connects how we grow food, make things, move and live. Explore those connections freely. There is no prescribed route.</p><h3>A sketch, not a measurement.</h3><p>Every concentration, source share, trend and pathway location in this prototype is invented. The particles are an artistic interpretation. Geographic positions locate cities; they do not locate verified emissions sources.</p><p>Facility emissions cannot be read as local exposure. Real attribution would require consistent emissions inventories, atmospheric chemistry, transport modeling and validation.</p><h3>The science behind the ideas</h3><div className="evidence-links">{evidence.map(e=><a key={e.url} href={e.url} target="_blank" rel="noreferrer">{e.title}<ArrowSquareOut size={17}/></a>)}</div><small>Earth texture: three.js example assets. Boundaries: Natural Earth / world-atlas. No live pollution feeds.</small></>}
   {modal==='compare'&&<><span className="eyebrow">ONE ATMOSPHERE, DIFFERENT PLACES</span><h2>Put two places<br/>in perspective.</h2><div className="compare-grid">{[city,compare].map((c,i)=><div className="comparison-place" key={i}><span className="eyebrow">{i?'COMPARE WITH':'YOUR SELECTED PLACE'}</span>{i?<select aria-label="Comparison city" value={compare.id} onChange={e=>setCompare(cities.find(c=>c.id===e.target.value))}>{cities.filter(c=>c.id!==city.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:<h3>{c.name}</h3>}<span>{c.country}</span><div className="compare-number">{concentrations(c,year,month,scenario)}<small>µg/m³ PM₂.₅</small></div>{systems.map((s,j)=><div className="compare-mix" key={s.id}><span>{s.name}</span><div><i style={{width:c.profile[j]*3+'%',background:s.color}}/></div><strong>{c.profile[j]}%</strong></div>)}</div>)}</div><div className="comparison-footer"><p>{seasons[month]} {year} · Fictional concentrations and source shares.<br/>These differences are not evidence about either city.</p><button onClick={()=>{chooseCity(compare);setModal(null);}}>Explore {compare.name}<Crosshair size={17}/></button></div></>}
   {modal==='scenario'&&<><span className="eyebrow">A HYPOTHETICAL CHANGE</span><h2>Imagine less<br/>combustion.</h2><p>Try reducing the demo emissions intensity of energy, industry and transportation. Watch the illustrative particle field become less dense.</p><div className="scenario-value"><strong>{scenario}%</strong><span>reduction in demo intensity</span></div><input type="range" min="0" max="80" value={scenario} aria-label="Hypothetical emission reduction" onChange={e=>setScenario(+e.target.value)}/><div className="scenario-labels"><span>No change</span><span>80% less</span></div><div className="scenario-result"><span>FICTIONAL PM₂.₅ RESPONSE</span><strong>{concentrations(city,year,month,0)} <span>to</span> {pm} <small>µg/m³</small></strong></div><p className="scenario-caveat">This uses a simple invented response rule, not an atmospheric model. Real effects depend on chemistry, weather and the mix of sources; they are not necessarily linear.</p><button className="apply-scenario" onClick={()=>setModal(null)}>Explore this atmosphere</button><button className="reset-scenario" onClick={()=>setScenario(0)}>Reset change</button></>}
  </section></div>}
 </main>;
}
export default App;
